In [1]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

1. sentence transformer
2. langchain hugging
3. transformer

In [2]:
%pip install sentence-transformers

Note: you may need to restart the kernel to use updated packages.


In [3]:
from sentence_transformers import  SentenceTransformer

c:\Users\amit6\Desktop\NLP-Krish _Naik\GenAI_KrishNLPBatch\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
model = SentenceTransformer('all-mpnet-base-v2')

In [5]:
sentences[0]

'I ate dinner.'

In [6]:
model.encode(sentences[0]) #vector representation of entire sentence of zero indexing

array([-1.58598404e-02,  4.59825173e-02, -1.46349818e-02, -4.85908873e-02,
       -3.60325840e-03,  3.17664146e-02, -3.27771418e-02,  2.11894829e-02,
        1.07366778e-02,  2.50182953e-02,  1.58237386e-02,  1.24069881e-02,
        1.62089840e-02, -1.30435321e-02,  4.58446704e-02,  4.40269448e-02,
        4.57801856e-02, -4.32263082e-03,  1.87807102e-02,  5.22198528e-03,
       -1.86415911e-02, -7.11808586e-03,  3.01358867e-02,  1.70696210e-02,
       -1.53763434e-02,  3.34171318e-02, -6.55886205e-03,  1.58591419e-02,
        1.37040094e-02, -2.02766694e-02,  3.26632746e-02,  5.48364734e-03,
       -3.53351831e-02, -1.06665134e-01,  1.85711599e-06,  3.66638750e-02,
       -1.71335191e-02,  3.34468633e-02, -6.43021762e-02,  6.90795779e-02,
        2.50845291e-02,  2.89431792e-02, -8.98414105e-03, -1.84545703e-02,
        2.81152204e-02, -2.34797820e-02,  1.21612735e-02,  6.25150502e-02,
       -8.58704373e-02, -1.84618833e-03,  7.95865897e-03, -8.42522457e-02,
       -2.26104036e-02,  

In [ ]:
model.encode(sentences[0]).shape #768 dimension, means 768 numbers are numbers are present inside the embedding

(768,)

In [8]:
%pip install langchain
%pip install langchain-community

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [9]:
from langchain.embeddings import HuggingFaceEmbeddings

In [10]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [11]:
model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)

C:\Users\amit6\AppData\Local\Temp\ipykernel_10672\2861529945.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)


In [12]:
embedding_vector = embeddings.embed_query(sentences[0])

In [13]:
embedding_vector

[-0.01585984043776989,
 0.045982517302036285,
 -0.014634981751441956,
 -0.04859088733792305,
 -0.003603258403018117,
 0.031766414642333984,
 -0.03277714177966118,
 0.021189482882618904,
 0.010736677795648575,
 0.025018295273184776,
 0.015823738649487495,
 0.012406988069415092,
 0.016208983957767487,
 -0.013043532148003578,
 0.0458446703851223,
 0.044026944786310196,
 0.04578018561005592,
 -0.0043226308189332485,
 0.01878071017563343,
 0.005221985280513763,
 -0.01864159107208252,
 -0.007118085864931345,
 0.03013588674366474,
 0.0170696210116148,
 -0.01537634339183569,
 0.03341713175177574,
 -0.0065588620491325855,
 0.015859141945838928,
 0.013704009354114532,
 -0.020276669412851334,
 0.03266327455639839,
 0.005483647342771292,
 -0.03533518314361572,
 -0.10666513442993164,
 1.8571159898783662e-06,
 0.03666387498378754,
 -0.017133519053459167,
 0.033446863293647766,
 -0.06430217623710632,
 0.06907957792282104,
 0.02508452907204628,
 0.028943179175257683,
 -0.008984141051769257,
 -0.018454

In [14]:
len(embedding_vector)

768

one more approach with tranformer huggingface libary

In [15]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [17]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

c:\Users\amit6\Desktop\NLP-Krish _Naik\GenAI_KrishNLPBatch\venv\lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\amit6\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [18]:
model=BertModel.from_pretrained("bert-base-uncased")

In [19]:
text="follow sunny for genai learning"

In [20]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [21]:
input_ids=encoding["input_ids"]

In [22]:
attention_mask=encoding["attention_mask"]

In [23]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [24]:
word_embeddings

tensor([[[-0.0046, -0.1060, -0.0177,  ...,  0.0474,  0.0697,  0.2605],
         [ 0.8739, -0.1599,  0.5948,  ...,  0.4223,  0.2269, -0.1508],
         [ 0.0209, -0.3746, -0.2735,  ...,  0.3497,  0.0062, -0.4563],
         ...,
         [-0.2692, -0.4198, -0.1005,  ..., -0.0563, -0.2520, -0.6442],
         [-0.4552, -0.7338, -0.2614,  ...,  0.8366,  0.2496, -0.1972],
         [ 0.8920,  0.1769, -0.2345,  ...,  0.3265, -0.7962, -0.2090]]])

In [25]:
word_embeddings.shape

torch.Size([1, 8, 768])

In [26]:
input_ids[0]

tensor([  101,  3582, 11559,  2005,  8991,  4886,  4083,   102])

In [27]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [28]:
decode

'follow sunny for genai learning'